source 'https://github.com/CocoaPods/Specs'
source 'https://git-apac.internal.tigerspike.com/ios/tscocoapodsspec.git'

platform :ios, '<%= deployment_target %>'

# Add Application pods here
pod 'HockeySDK'
pod 'TSCommons'
pod 'Calabash', :configuration => ['calabash']


<% if enable_settings && use_cocoapods %>
# Copy acknowledgements to the Settings.bundle

post_install do | installer |
  require 'fileutils'

  pods_acknowledgements_path = 'Pods/Target Support Files/Pods/Pods-Acknowledgements.plist'
  settings_bundle_path = Dir.glob("**/*Settings.bundle*").first

  if File.file?(pods_acknowledgements_path)
    puts 'Copying acknowledgements to Settings.bundle'
    FileUtils.cp_r(pods_acknowledgements_path, "#{settings_bundle_path}/Acknowledgements.plist", :remove_destination => true)
  end
end
<% end %>